# Channel Speak Layer
#
# Contributes to a channel conversation when impulse threshold is reached.
# Context includes channel insights, user insights for active participants,
# dyad insights, and recent channel messages.
# Model: Sonnet (moderate tier) for natural conversation.

name: channel-speak
category: participation
description: |
  Contribute to a channel conversation when impulse threshold reached.
  Triggered when channel topic impulse exceeds threshold.

trigger: impulse_threshold
target_category: channel

nodes:
  - name: fetch_channel_messages
    type: fetch_messages
    params:
      max_messages: 25
      lookback_hours: 24
      use_greater: true

  - name: fetch_channel_context
    type: fetch_insights
    params:
      max_per_topic: 10
      include_users: true
      user_max_per_topic: 5
      include_dyads: true
      dyad_max_per_topic: 5

  - name: generate
    type: llm_call
    params:
      prompt_template: conversation/channel-speak.jinja2
      model: moderate
      max_tokens: 1024
      temperature: 0.8

  - name: send
    type: output
    params:
      destination: discord
      review: true
